AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  SuggestExtensions: false

Lint/UnusedBlockArgument:
  AutoCorrect: false
Lint/UnusedMethodArgument:
  AutoCorrect: false

Metrics:
  Enabled: false
Naming:
  Enabled: false
Style:
  Enabled: false
