AllCops:
  TargetRubyVersion: 2.5
  NewCops: disable
  SuggestExtensions: false

Lint/UnusedBlockArgument:
  AutoCorrect: false
Lint/UnusedMethodArgument:
  AutoCorrect: false

Metrics:
  Enabled: false

# ModBus's master/slave terminology can be updated, but not now
Naming/InclusiveLanguage:
  Enabled: false

Style:
  Enabled: false
